Repository DevelopDesignDayDay/attendance-spring-api, pull requests merged in 2021-08, with the labels that each got.

#22 [TASK] JWT 생성 로직 개발
  build.gradle.kts
  src/main/kotlin/com/example/attendanceapimono/AttendanceApiMonoApplication.kt
  src/main/kotlin/com/example/attendanceapimono/adapter/infra/security/AuthProperties.kt
  src/main/kotlin/com/example/attendanceapimono/adapter/infra/security/AuthenticationManager.kt
  src/main/kotlin/com/example/attendanceapimono/adapter/infra/security/CorsConfig.kt
  src/main/kotlin/com/example/attendanceapimono/adapter/infra/security/PermitSet.kt
  src/main/kotlin/com/example/attendanceapimono/adapter/infra/security/SecurityConfig.kt
  src/main/kotlin/com/example/attendanceapimono/adapter/infra/security/SecurityConst.kt
  src/main/kotlin/com/example/attendanceapimono/adapter/infra/security/SecurityContextRepository.kt
  src/main/kotlin/com/example/attendanceapimono/adapter/infra/security/TokenProvider.kt
  src/main/kotlin/com/example/attendanceapimono/adapter/infra/security/UserPrinciple.kt
  src/main/kotlin/com/example/attendanceapimono/adapter/present/UserController.kt
  src/main/kotlin/com/example/attendanceapimono/adapter/present/api/UserAPI.kt
  src/main/kotlin/com/example/attendanceapimono/application/UserService.kt
  src/main/kotlin/com/example/attendanceapimono/application/dto/user/SignIn.kt
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/test/kotlin/com/example/attendanceapimono/TokenProviderTest.kt
Labels: :octocat: HellP, 🔨 TASK

#26 refactor security
  src/main/kotlin/com/example/attendanceapimono/adapter/infra/config/SecurityConfig.kt
  src/main/kotlin/com/example/attendanceapimono/adapter/infra/security/CorsConfig.kt
  src/main/kotlin/com/example/attendanceapimono/adapter/infra/security/SecurityContextRepository.kt
  src/main/kotlin/com/example/attendanceapimono/adapter/infra/security/TokenProvider.kt
  src/main/kotlin/com/example/attendanceapimono/adapter/infra/security/UserPrincipal.kt
  src/main/kotlin/com/example/attendanceapimono/application/UserService.kt
Labels: ⭐ 리뷰 필요!, :octocat: R.bertKo

#34 feat: re-sign 및 회원가입시 token response 주지 않는 부분 추가
  src/main/kotlin/com/example/attendanceapimono/adapter/present/UserController.kt
  src/main/kotlin/com/example/attendanceapimono/adapter/present/api/UserAPI.kt
  src/main/kotlin/com/example/attendanceapimono/application/UserService.kt
  src/main/kotlin/com/example/attendanceapimono/application/dto/user/ReSign.kt
  src/main/kotlin/com/example/attendanceapimono/application/dto/user/ReSignResponse.kt
  src/main/kotlin/com/example/attendanceapimono/application/exception/UserException.kt
  src/main/kotlin/com/example/attendanceapimono/domain/user/User.kt
  src/main/kotlin/com/example/attendanceapimono/util/mono.kt
Labels: ⭐ 리뷰 필요!, :octocat: R.bertKo, 🔨 TASK

#35 fix: 스웨거 문서 픽스
  src/main/kotlin/com/example/attendanceapimono/adapter/present/api/JWTTokenV1.kt
  src/main/kotlin/com/example/attendanceapimono/adapter/present/api/UserAPI.kt
Labels: ⭐ 리뷰 필요!, :octocat: R.bertKo, :lemon: EZPZ PR
